### ISSUE TITLE
Clarify when multiple in prf field can occur

### ISSUE THREAD

**Issue by burdiyan** [ucan-wg/spec#147]
I wonder in which situations multiple tokens can be "mentioned" in the `prf` field?

As far as I understood, multiple levels of delegations would normally be expressed as multiple levels of nesting, i.e. only one item in `prf` field at each level (see example bellow). But since `prf` is an array, I guess there're situations where multiple items can be present, but I can't figure out when it's useful.

Example:

```javascript
aliceToken = {
    "iss": "root-principal",
    "aud": "alice",
    "prf": [],
}

bobToken = {
    "iss": "alice",
    "aud": "bob",
    "prf": [
        aliceToken
    ]
}

carolToken = {
    "iss": "bob",
    "aud": "carol",
    "prf": [
        bobToken
    ]
}
```

**Comment by matheus23** [comment]
One example is rights amplification: https://github.com/ucan-wg/spec#64-rights-amplification

Another example is simply if you want to do an invocation which needs multiple capabilities, that you *have* been granted access to, but via separate UCANs. In these cases you construct a new UCAN with both capabilities in the attenuations and attach both UCANs to the proofs.

Generally, if multiple proofs exist, then a capability is deemed "valid" if *any* of the proofs is a valid proof for a capability.

This way, a user can also future-proof themselves against revocations: By attaching multiple different kinds of proofs to their UCAN, their invocation may still be valid if only one of the UCANs used in the proof array is revoked (e.g. because one of the persons that delegated a UCAN to them had their keys compromised).
