### ISSUE TITLE
Principal IDs and signature verification

### ISSUE THREAD

**Issue by chunningham** [ucan-wg/spec#77]
The current wording of 3.2.1 identifies the `iss`uer and `aud`ience as standalone DIDs, as well as specifying:

> The token MUST be signed with the private key associated with the DID in the `iss` field.

This is fine for `did:key`, as one `did:key:...` corresponds exactly and immutably with one private key. However this is a special case for DID methods, which in general do not enforce such a 1:1 correspondence (indeed a DID may even have 0 associated key pairs). The next sentence specifies:

> Implementations MUST include the [did:key method](https://w3c-ccg.github.io/did-method-key/), and MAY be augmented with [additional DID methods](https://www.w3.org/TR/did-core/).

In the general case of a DID document referencing multiple private keys (and which may be mutable), identifying the issuer by DID alone is insufficient for identifying the particular public key which can be used to verify the signature, making the augmentation with additional methods beyond `did:key` impractical or at least not performant.

Is it possible to change the `iss` (and perhaps the `aud`) field(s) to (perhaps optionally) contain a DID URL with a `#fragment` which identifies the exact key/verification method used to issue/verify the UCAN (e.g. `iss: "did:ion:my_did#my_ucan_key"`)? Alternatively, could an entry in the UCAN header be used for this purpose?

Particularly in the case of methods which use a public-key-hash (e.g. for `did:pkh` DIDs coming from platforms using non-recoverable signatures like ed25519), it could be necessary to even embed an entire public key in the message (or header) for the signature to be verifiable.

**Comment by expede** [comment]
Oh, yes, we should be more clear about that in the spec 💯 The hash fragment for key types that can have multiple keys is valid, but we don't have other DIDs implemented anywhere today (aside from an ION proof of concept).

I'll add that to the 0.9 PR shortly 👍

**Comment by clehner** [comment]
Another option would be to use a different header parameter (e.g. `kid`) for the verification method id. Then the issuer id could remain a DID, rather than being either a DID or a key id (DID URL). Reducing overloading and optionality might allow for simpler implementations and spec? But it would also increase the size of the payloads, which may be undesirable.

Using `kid` for the key id (DID URL) and `iss` for the issuer (DID) is what some JWT verifiable credential implementations are doing in <https://identity.foundation/JWS-Test-Suite/>, as allowed in https://www.w3.org/TR/vc-data-model/#jwt-encoding .

---

If issuer may have a hash fragment, maybe the spec should recommend one form or the other? e.g. if the DID has an unambiguous public key for capability delegation purposes, then the hash fragment should be omitted, otherwise the hash fragment must be included. Otherwise it could be a potential interoperability issue if if implementations only supporting `did:key` don't support the hash fragment and implementations supporting multiple DID methods always include the hash fragment.
